# Generated by Django 3.2.9 on 2021-11-18 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre_libro', models.CharField(max_length=50)),
                ('materia_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio_pruebas.materia')),
            ],
        ),
    ]
